apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: drools-rules-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/dotcomrow/rules-apps.git
        revision: prod
        directories:
          - path: apps/*
  template:
    metadata:
      name: rules-{{path.basename}}
    spec:
      project: rules-apps
      source:
        repoURL: https://github.com/dotcomrow/rules-apps.git
        targetRevision: prod
        path: "{{path}}"
        kustomize: {}
      destination:
        server: https://kubernetes.default.svc
        namespace: drools
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
