apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: drools-rules-apps
  namespace: argocd
spec:
  generators:
    - scmProvider:
        github:
          organization: dotcomrow
          api: https://api.github.com
          tokenRef:
            secretName: github-scm-token
            key: token
        filters:
          - pathsExist:
              - manifests/register-container-job.yaml
              - manifests/workbench-import-job.yaml
  template:
    metadata:
      name: rules-{{repository}}
    spec:
      project: rules-apps
      source:
        repoURL: "{{url}}"
        targetRevision: prod
        path: manifests
        kustomize:
          commonLabels:
            app.kubernetes.io/managed-by: argocd
      destination:
        server: https://kubernetes.default.svc
        namespace: drools
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
