apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rules-apps
  namespace: argocd
spec:
  description: Project for rules-apps app-of-apps
  sourceRepos:
    - '*'
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: drools
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
